### ISSUE TITLE
Error in parallel::mclapply

### ISSUE THREAD

**Issue by Rohit-Satyam** [gversmee/dbgap2x#21]
Hi Authors!!

I am trying to use this package. When I run the exemplary command in R i.e. `search.dbgap("Jackson")` it throws the following error: 

```r
Error in parallel::mclapply(mc.cores = getOption("mc.cores", parallel::detectCores()),  : 
  'mc.cores' > 1 is not supported on Windows
```

Please help me understand how to deal with this?

**Comment by mikaeldusenne** [comment]
Hi @Rohit-Satyam , thanks for reaching out.

unfortunately this package was developped with unix systems in mind. 
Since the `mclapply` function from the `parallel` package relies on the fork mechanism of *nix operating systems, it does not work on windows.

I would advise you to try to use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (untested).
If that doesn't work, I'm afraid you will need to find a Mac / Linux system to run the app.

Good luck!

Mikael
